version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - ./client/.env
    depends_on:
      - backend

  backend:
    build:
      context: ./serveur
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./serveur/.env
    depends_on:
      - minio
      - ollama

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=passer123
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama

volumes:
  db-data:
  minio-data:
  ollama-data:
