apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: aminataba01/backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: NODE_ENV
          value: "production"
        - name: MONGO_URI
          value: "mongodb+srv://user1:MY0bDj8LQJJVZXW1@cluster0.nnnor.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
        - name: MINIO_ENDPOINT
          value: "minio-service:9000"
        - name: MINIO_ACCESS_KEY
          value: "admin"
        - name: MINIO_SECRET_KEY
          value: "passer123"
        - name: MINIO_BUCKET
          value: "autoeval"
        - name: MINIO_USE_SSL
          value: "false"
        - name: OLLAMA_API_URL
          value: "http://ollama-service:11434"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP